# Your wrangler.toml file should look something like this:
name = "saral-commerce"
compatibility_date = "2024-03-21"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"




[[d1_databases]]
binding = "DB"
database_name = "saral-commerce"
database_id = "2d810400-1b49-47a9-8735-efce746beb4e"
preview_database_id = "2d810400-1b49-47a9-8735-efce746beb4e"
